name: Release Electron App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js (with Yarn)
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build Electron app
        run: yarn build

      - name: Create a Git tag
        id: create_tag
        run: |
          $VERSION = (Get-Content package.json | ConvertFrom-Json).version
          echo "VERSION=$VERSION" >> $env:GITHUB_ENV
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Check if tag exists
          $tagExists = git ls-remote --tags origin "refs/tags/v$VERSION"
          
          if ($tagExists) {
            echo "Tag v$VERSION already exists. Skipping tag creation."
            echo "TAG_EXISTS=true" >> $env:GITHUB_ENV
          } else {
            git tag "v$VERSION"
            git push origin "v$VERSION"
            echo "TAG_EXISTS=false" >> $env:GITHUB_ENV
          }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        if: env.TAG_EXISTS == 'false'
        with:
          files: |
            ./dist/**/*
          tag_name: v${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release to GitHub
        if: env.TAG_EXISTS == 'false'
        run: yarn electron-builder --win